// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzaRnYloC0v7xXe9TBtOAiXECPP0X_maI',
    appId: '1:285311374693:web:f668f8225e02bbf33c7d8c',
    messagingSenderId: '285311374693',
    projectId: 'chat-a7ad0',
    authDomain: 'chat-a7ad0.firebaseapp.com',
    storageBucket: 'chat-a7ad0.appspot.com',
    measurementId: 'G-WVJN6V39MK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByaiNYOj6XR-PclC-UAB14Gep4I1xsRPo',
    appId: '1:285311374693:android:416a3b1c43d699dd3c7d8c',
    messagingSenderId: '285311374693',
    projectId: 'chat-a7ad0',
    storageBucket: 'chat-a7ad0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4VroPjQAEgjC9C8pgFUp11gMinaSrRyE',
    appId: '1:285311374693:ios:5d39d943e0f6a05b3c7d8c',
    messagingSenderId: '285311374693',
    projectId: 'chat-a7ad0',
    storageBucket: 'chat-a7ad0.appspot.com',
    iosBundleId: 'com.social.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4VroPjQAEgjC9C8pgFUp11gMinaSrRyE',
    appId: '1:285311374693:ios:5d39d943e0f6a05b3c7d8c',
    messagingSenderId: '285311374693',
    projectId: 'chat-a7ad0',
    storageBucket: 'chat-a7ad0.appspot.com',
    iosBundleId: 'com.social.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzaRnYloC0v7xXe9TBtOAiXECPP0X_maI',
    appId: '1:285311374693:web:3c9cb5ef354a28993c7d8c',
    messagingSenderId: '285311374693',
    projectId: 'chat-a7ad0',
    authDomain: 'chat-a7ad0.firebaseapp.com',
    storageBucket: 'chat-a7ad0.appspot.com',
    measurementId: 'G-FGW764K5QD',
  );

}